spring:
  datasource:
    url: jdbc:mysql://10.1.2.4:3306/tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: hb-mysql
    password: sylincom@123
  redis:
    host: 10.1.2.4 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: sylincom # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.gu.tiny: debug