server:
  port: 8080

spring:
  application:
    name: tiny
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gu.tiny.modules.ums.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

redis:
  database: tiny
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resource:list'
  expire:
    common: 86400 # 24小时
gu:
  swagger-manager:
    api-base-package: com.gu.tiny

  jwt:
    header: Authorization #JWT存储的请求头
    base64-secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMI
    token-start-with: 'Bearer '
    token-validity-in-seconds: 604800 #JWT的超期限时间(60*60*24*7)
  secure:
    ignored:
      urls: #安全路径白名单
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /admin/login
        - /admin/register
        - /admin/info
        - /admin/logout
